### ISSUE TITLE
Quotes in monster's name

### ISSUE THREAD

**Issue by DarknessCatt** [DarknessCatt/YGODomainGenerator#18]
Having Magician's Rod (7084129) as your deckmaster causes this:

> Exception in Tkinter callback
> Traceback (most recent call last):
>   File "C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python311\Lib\tkinter\__init__.py", line 1948, in __call__
>   File "C:\Users\WDAGUtilityAccount\Desktop\a\interfaces\gui.py", line 104, in OnIdChanged
>   File "C:\Users\WDAGUtilityAccount\Desktop\a\interfaces\gui.py", line 46, in GetDeckMasterAndDomain
>   File "C:\Users\WDAGUtilityAccount\Desktop\a\classes\domain.py", line 174, in __init__
>   File "C:\Users\WDAGUtilityAccount\Desktop\a\classes\domain.py", line 133, in GetCardDomainFromDesc
>   File "C:\Users\WDAGUtilityAccount\Desktop\a\classes\sql.py", line 115, in GetMonsterByName
> sqlite3.OperationalError: near "s": syntax error

Probably need to escape the SQL queries.

**Comment by DarknessCatt** [comment]
fixed by #23
